version: "2"
services:
  go_api:
    build: "./backend"
    environment:
      - GOPATH=/go
      - CODER_KEY=123456789012345678901234
      - DB_FILE=/go/data/data.db
    command: /bin/sh -c "go build -o main && ./main"
    ports:
    - "8080"

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    volumes:
      - ${STATIC_DIR}:/var/www/
    depends_on:
      - "go_api"
