version: "2"
services:
  go_api:
    build: "./backend"
    environment:
      - GOPATH=/go
      - CODER_KEY=${CODER_KEY}
      - DB_FILE=/go/data/data.db
    command: /bin/sh -c "go build -o main && ./main"
    ports:
    - "8080"

  ng_app:
    build: "./frontend"
    ports:
      - '8081:4200'
      - '49153:49153'
    volumes:
    - /home/ilya/prog/projects/task_manager/frontend/:/usr/src/app/
    command: bash -c "npm start"
    depends_on:
      - "go_api"

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "ng_app"
