version: "2"
services:
  ng_app:
    build: "./frontend"
    ports:
      - '8081:4200'
      - '49153:49153'
    volumes:
    - ${FRONTEND_DIR}:/usr/src/app/
    command: bash -c "npm start"
    depends_on:
      - "go_api"

  nginx:
    build: "./nginx/dev"
    ports:
      - "80:80"
    depends_on:
      - "ng_app"
