version: "2"
services:
  go_api:
    build: "./backend"
    environment:
      - GOPATH=/go
      - CODER_KEY=${CODER_KEY}
      - DB_FILE=/go/data/data.db
    command: /bin/sh -c "go build -o main && ./main"
    ports:
      - "8080"
